cmake -B build-wii --toolchain "$DEVKITPRO/cmake/Wii.cmake" -DSDL_OPENGL=OFF -DD2MOO_INSTALL=OFF -DD2MOO_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF -DWHOA_STORM_FLAVOR=DIABLO2 -DCMAKE_BUILD_TYPE=Debug .
